name: CI

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Update certificates sudo
        run: sudo update-ca-certificates 
        continue-on-error: true

      - name: Download sber id sdk archive
        run: aria2c https://developer.sberbank.ru/doc/files/sberbankid_sdk_android_v~1~1~2~zip
